version: '3'

services:
  backend:
    image: darkposss/ai-adviser:backend
    container_name: my-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: darkposss/ai-adviser:frontend
    container_name: my-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
