version: '3'

services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "80:80"