version: '3'

services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
