name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t darkposss/ai-adviser:frontend ./frontend

      - name: Build backend image
        run: docker build -t darkposss/ai-adviser:backend ./backend

      - name: Push frontend image
        run: docker push darkposss/ai-adviser:frontend

      - name: Push backend image
        run: docker push darkposss/ai-adviser:backend
